//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaestebuch_Sebastian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eintraege
    {
        public int Id { get; set; }
        public string IP { get; set; }
        public string Name { get; set; }
        public System.DateTime Besuchsdatum { get; set; }
        public string Kommentar { get; set; }
        public Nullable<int> Autorisiert_ID { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
