//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaestebuch_Sebastian.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Logs
    {
        public int Id { get; set; }
        public Nullable<int> Admin_ID { get; set; }
        public string Aktion { get; set; }
        public string IP { get; set; }
        public Nullable<DateTime> Zeit { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
